package com.time.app.ui.icons

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.twotone.AccessAlarm
import androidx.compose.material.icons.twotone.Check
import androidx.compose.material.icons.twotone.FitnessCenter
import androidx.compose.material.icons.twotone.Home
import androidx.compose.material.icons.twotone.Person
import androidx.compose.material.icons.twotone.School
import androidx.compose.material.icons.twotone.Settings
import androidx.compose.material.icons.twotone.Star
import androidx.compose.material.icons.twotone.Timer
import androidx.compose.material.icons.twotone.Work
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp
import com.time.app.R

object IconRepository {

    // Predefined ImageVector icons
    val allIcons: Map<String, ImageVector> = mapOf(
        "Home" to Icons.TwoTone.Home,
        "Work" to Icons.TwoTone.Work,
        "School" to Icons.TwoTone.School,
        "Star" to Icons.TwoTone.Star,
        "Fitness" to Icons.TwoTone.FitnessCenter,
        "Person" to Icons.TwoTone.Person,
        "Check" to Icons.TwoTone.Check,
        "Alarm" to Icons.TwoTone.AccessAlarm,
        "Timer" to Icons.TwoTone.Timer,
        "Settings" to Icons.TwoTone.Settings
    )

    // Additional Char-based icons from .codepoints
    val fontCodepointIcons: Map<String, Char> = mapOf(
        "10K" to '\ue951',
        "10Mp" to '\ue952',
        "11Mp" to '\ue953',
        "123" to '\ueb8d',
        "12Mp" to '\ue954',
        "13Mp" to '\ue955',
        "14Mp" to '\ue956',
        "15Mp" to '\ue957',
        "16Mp" to '\ue958',
        "17Mp" to '\ue959',
        "18 Up Rating" to '\uf8fd',
        "18Mp" to '\ue95a',
        "19Mp" to '\ue95b',
        "1K" to '\ue95c',
        "1K Plus" to '\ue95d',
        "1X Mobiledata" to '\uefcd',
        "20Mp" to '\ue95e',
        "21Mp" to '\ue95f',
        "22Mp" to '\ue960',
        "23Mp" to '\ue961',
        "24Mp" to '\ue962',
        "2K" to '\ue963',
        "2K Plus" to '\ue964',
        "2Mp" to '\ue965',
        "30Fps" to '\uefce',
        "30Fps Select" to '\uefcf',
        "360" to '\ue577',
        "3D Rotation" to '\ue84d',
        "3G Mobiledata" to '\uefd0',
        "3K" to '\ue966',
        "3K Plus" to '\ue967',
        "3Mp" to '\ue968',
        "3P" to '\uefd1',
        "4G Mobiledata" to '\uefd2',
        "4G Plus Mobiledata" to '\uefd3',
        "4K" to '\ue072',
        "4K Plus" to '\ue969',
        "4Mp" to '\ue96a',
        "5G" to '\uef38',
        "5K" to '\ue96b',
        "5K Plus" to '\ue96c',
        "5Mp" to '\ue96d',
        "60Fps" to '\uefd4',
        "60Fps Select" to '\uefd5',
        "6 Ft Apart" to '\uf21e',
        "6K" to '\ue96e',
        "6K Plus" to '\ue96f',
        "6Mp" to '\ue970',
        "7K" to '\ue971',
        "7K Plus" to '\ue972',
        "7Mp" to '\ue973',
        "8K" to '\ue974',
        "8K Plus" to '\ue975',
        "8Mp" to '\ue976',
        "9K" to '\ue977',
        "9K Plus" to '\ue978',
        "9Mp" to '\ue979',
        "Abc" to '\ueb94',
        "Ac Unit" to '\ueb3b',
        "Access Alarm" to '\ue190',
        "Access Alarms" to '\ue191',
        "Access Time" to '\ue192',
        "Access Time Filled" to '\uefd6',
        "Accessibility" to '\ue84e',
        "Accessibility New" to '\ue92c',
        "Accessible" to '\ue914',
        "Accessible Forward" to '\ue934',
        "Account Balance" to '\ue84f',
        "Account Balance Wallet" to '\ue850',
        "Account Box" to '\ue851',
        "Account Circle" to '\ue853',
        "Account Tree" to '\ue97a',
        "Ad Units" to '\uef39',
        "Adb" to '\ue60e',
        "Add" to '\ue145',
        "Add A Photo" to '\ue439',
        "Add Alarm" to '\ue193',
        "Add Alert" to '\ue003',
        "Add Box" to '\ue146',
        "Add Business" to '\ue729',
        "Add Card" to '\ueb86',
        "Add Chart" to '\ue97b',
        "Add Circle" to '\ue147',
        "Add Circle Outline" to '\ue148',
        "Add Comment" to '\ue266',
        "Add Home" to '\uf8eb',
        "Add Home Work" to '\uf8ed',
        "Add Ic Call" to '\ue97c',
        "Add Link" to '\ue178',
        "Add Location" to '\ue567',
        "Add Location Alt" to '\uef3a',
        "Add Moderator" to '\ue97d',
        "Add Photo Alternate" to '\ue43e',
        "Add Reaction" to '\ue1d3',
        "Add Road" to '\uef3b',
        "Add Shopping Cart" to '\ue854',
        "Add Task" to '\uf23a',
        "Add To Drive" to '\ue65c',
        "Add To Home Screen" to '\ue1fe',
        "Add To Photos" to '\ue39d',
        "Add To Queue" to '\ue05c',
        "Addchart" to '\uef3c',
        "Adf Scanner" to '\ueada',
        "Adjust" to '\ue39e',
        "Admin Panel Settings" to '\uef3d',
        "Adobe" to '\uea96',
        "Ads Click" to '\ue762',
        "Agriculture" to '\uea79',
        "Air" to '\uefd8',
        "Airline Seat Flat" to '\ue630',
        "Airline Seat Flat Angled" to '\ue631',
        "Airline Seat Individual Suite" to '\ue632',
        "Airline Seat Legroom Extra" to '\ue633',
        "Airline Seat Legroom Normal" to '\ue634',
        "Airline Seat Legroom Reduced" to '\ue635',
        "Airline Seat Recline Extra" to '\ue636',
        "Airline Seat Recline Normal" to '\ue637',
        "Airline Stops" to '\ue7d0',
        "Airlines" to '\ue7ca',
        "Airplane Ticket" to '\uefd9',
        "Airplanemode Active" to '\ue195',
        "Airplanemode Inactive" to '\ue194',
        "Airplanemode Off" to '\ue194',
        "Airplanemode On" to '\ue195',
        "Airplay" to '\ue055',
        "Airport Shuttle" to '\ueb3c',
        "Alarm" to '\ue855',
        "Alarm Add" to '\ue856',
        "Alarm Off" to '\ue857',
        "Alarm On" to '\ue858',
        "Album" to '\ue019',
        "Align Horizontal Center" to '\ue00f',
        "Align Horizontal Left" to '\ue00d',
        "Align Horizontal Right" to '\ue010',
        "Align Vertical Bottom" to '\ue015',
        "Align Vertical Center" to '\ue011',
        "Align Vertical Top" to '\ue00c',
        "All Inbox" to '\ue97f',
        "All Inclusive" to '\ueb3d',
        "All Out" to '\ue90b',
        "Alt Route" to '\uf184',
        "Alternate Email" to '\ue0e6',
        "Amp Stories" to '\uea13',
        "Analytics" to '\uef3e',
        "Anchor" to '\uf1cd',
        "Android" to '\ue859',
        "Animation" to '\ue71c',
        "Announcement" to '\ue85a',
        "Aod" to '\uefda',
        "Apartment" to '\uea40',
        "Api" to '\uf1b7',
        "App Blocking" to '\uef3f',
        "App Registration" to '\uef40',
        "App Settings Alt" to '\uef41',
        "App Shortcut" to '\ueae4',
        "Apple" to '\uea80',
        "Approval" to '\ue982',
        "Apps" to '\ue5c3',
        "Apps Outage" to '\ue7cc',
        "Architecture" to '\uea3b',
        "Archive" to '\ue149',
        "Area Chart" to '\ue770',
        "Arrow Back" to '\ue5c4',
        "Arrow Back Ios" to '\ue5e0',
        "Arrow Back Ios New" to '\ue2ea',
        "Arrow Circle Down" to '\uf181',
        "Arrow Circle Left" to '\ueaa7',
        "Arrow Circle Right" to '\ueaaa',
        "Arrow Circle Up" to '\uf182',
        "Arrow Downward" to '\ue5db',
        "Arrow Drop Down" to '\ue5c5',
        "Arrow Drop Down Circle" to '\ue5c6',
        "Arrow Drop Up" to '\ue5c7',
        "Arrow Forward" to '\ue5c8',
        "Arrow Forward Ios" to '\ue5e1',
        "Arrow Left" to '\ue5de',
        "Arrow Outward" to '\uf8ce',
        "Arrow Right" to '\ue5df',
        "Arrow Right Alt" to '\ue941',
        "Arrow Upward" to '\ue5d8',
        "Art Track" to '\ue060',
        "Article" to '\uef42',
        "Aspect Ratio" to '\ue85b',
        "Assessment" to '\ue85c',
        "Assignment" to '\ue85d',
        "Assignment Ind" to '\ue85e',
        "Assignment Late" to '\ue85f',
        "Assignment Return" to '\ue860',
        "Assignment Returned" to '\ue861',
        "Assignment Turned In" to '\ue862',
        "Assist Walker" to '\uf8d5',
        "Assistant" to '\ue39f',
        "Assistant Direction" to '\ue988',
        "Assistant Photo" to '\ue3a0',
        "Assured Workload" to '\ueb6f',
        "Atm" to '\ue573',
        "Attach Email" to '\uea5e',
        "Attach File" to '\ue226',
        "Attach Money" to '\ue227',
        "Attachment" to '\ue2bc',
        "Attractions" to '\uea52',
        "Attribution" to '\uefdb',
        "Audio File" to '\ueb82',
        "Audiotrack" to '\ue3a1',
        "Auto Awesome" to '\ue65f',
        "Auto Awesome Mosaic" to '\ue660',
        "Auto Awesome Motion" to '\ue661',
        "Auto Delete" to '\uea4c',
        "Auto Fix High" to '\ue663',
        "Auto Fix Normal" to '\ue664',
        "Auto Fix Off" to '\ue665',
        "Auto Graph" to '\ue4fb',
        "Auto Mode" to '\uec20',
        "Auto Stories" to '\ue666',
        "Autofps Select" to '\uefdc',
        "Autorenew" to '\ue863',
        "Av Timer" to '\ue01b',
        "Baby Changing Station" to '\uf19b',
        "Back Hand" to '\ue764',
        "Backpack" to '\uf19c',
        "Backspace" to '\ue14a',
        "Backup" to '\ue864',
        "Backup Table" to '\uef43',
        "Badge" to '\uea67',
        "Bakery Dining" to '\uea53',
        "Balance" to '\ueaf6',
        "Balcony" to '\ue58f',
        "Ballot" to '\ue172',
        "Bar Chart" to '\ue26b',
        "Batch Prediction" to '\uf0f5',
        "Bathroom" to '\uefdd',
        "Bathtub" to '\uea41',
        "Battery 0 Bar" to '\uebdc',
        "Battery 1 Bar" to '\uebd9',
        "Battery 20" to '\uf09c',
        "Battery 2 Bar" to '\uebe0',
        "Battery 30" to '\uf09d',
        "Battery 3 Bar" to '\uebdd',
        "Battery 4 Bar" to '\uebe2',
        "Battery 50" to '\uf09e',
        "Battery 5 Bar" to '\uebd4',
        "Battery 60" to '\uf09f',
        "Battery 6 Bar" to '\uebd2',
        "Battery 80" to '\uf0a0',
        "Battery 90" to '\uf0a1',
        "Battery Alert" to '\ue19c',
        "Battery Charging 20" to '\uf0a2',
        "Battery Charging 30" to '\uf0a3',
        "Battery Charging 50" to '\uf0a4',
        "Battery Charging 60" to '\uf0a5',
        "Battery Charging 80" to '\uf0a6',
        "Battery Charging 90" to '\uf0a7',
        "Battery Charging Full" to '\ue1a3',
        "Battery Full" to '\ue1a4',
        "Battery Saver" to '\uefde',
        "Battery Std" to '\ue1a5',
        "Battery Unknown" to '\ue1a6',
        "Beach Access" to '\ueb3e',
        "Bed" to '\uefdf',
        "Bedroom Baby" to '\uefe0',
        "Bedroom Child" to '\uefe1',
        "Bedroom Parent" to '\uefe2',
        "Bedtime" to '\uef44',
        "Bedtime Off" to '\ueb76',
        "Beenhere" to '\ue52d',
        "Bento" to '\uf1f4',
        "Bike Scooter" to '\uef45',
        "Biotech" to '\uea3a',
        "Blender" to '\uefe3',
        "Blind" to '\uf8d6',
        "Blinds" to '\ue286',
        "Blinds Closed" to '\uec1f',
        "Block" to '\ue14b',
        "Bloodtype" to '\uefe4',
        "Bluetooth" to '\ue1a7',
        "Bluetooth Audio" to '\ue60f',
        "Bluetooth Connected" to '\ue1a8',
        "Bluetooth Disabled" to '\ue1a9',
        "Bluetooth Drive" to '\uefe5',
        "Bluetooth Searching" to '\ue1aa',
        "Blur Circular" to '\ue3a2',
        "Blur Linear" to '\ue3a3',
        "Blur Off" to '\ue3a4',
        "Blur On" to '\ue3a5',
        "Bolt" to '\uea0b',
        "Book" to '\ue865',
        "Book Online" to '\uf217',
        "Bookmark" to '\ue866',
        "Bookmark Add" to '\ue598',
        "Bookmark Added" to '\ue599',
        "Bookmark Border" to '\ue867',
        "Bookmark Outline" to '\ue867',
        "Bookmark Remove" to '\ue59a',
        "Bookmarks" to '\ue98b',
        "Border All" to '\ue228',
        "Border Bottom" to '\ue229',
        "Border Clear" to '\ue22a',
        "Border Color" to '\ue22b',
        "Border Horizontal" to '\ue22c',
        "Border Inner" to '\ue22d',
        "Border Left" to '\ue22e',
        "Border Outer" to '\ue22f',
        "Border Right" to '\ue230',
        "Border Style" to '\ue231',
        "Border Top" to '\ue232',
        "Border Vertical" to '\ue233',
        "Boy" to '\ueb67',
        "Branding Watermark" to '\ue06b',
        "Breakfast Dining" to '\uea54',
        "Brightness 1" to '\ue3a6',
        "Brightness 2" to '\ue3a7',
        "Brightness 3" to '\ue3a8',
        "Brightness 4" to '\ue3a9',
        "Brightness 5" to '\ue3aa',
        "Brightness 6" to '\ue3ab',
        "Brightness 7" to '\ue3ac',
        "Brightness Auto" to '\ue1ab',
        "Brightness High" to '\ue1ac',
        "Brightness Low" to '\ue1ad',
        "Brightness Medium" to '\ue1ae',
        "Broadcast On Home" to '\uf8f8',
        "Broadcast On Personal" to '\uf8f9',
        "Broken Image" to '\ue3ad',
        "Browse Gallery" to '\uebd1',
        "Browser Not Supported" to '\uef47',
        "Browser Updated" to '\ue7cf',
        "Brunch Dining" to '\uea73',
        "Brush" to '\ue3ae',
        "Bubble Chart" to '\ue6dd',
        "Bug Report" to '\ue868',
        "Build" to '\ue869',
        "Build Circle" to '\uef48',
        "Bungalow" to '\ue591',
        "Burst Mode" to '\ue43c',
        "Bus Alert" to '\ue98f',
        "Business" to '\ue0af',
        "Business Center" to '\ueb3f',
        "Cabin" to '\ue589',
        "Cable" to '\uefe6',
        "Cached" to '\ue86a',
        "Cake" to '\ue7e9',
        "Calculate" to '\uea5f',
        "Calendar Month" to '\uebcc',
        "Calendar Today" to '\ue935',
        "Calendar View Day" to '\ue936',
        "Calendar View Month" to '\uefe7',
        "Calendar View Week" to '\uefe8',
        "Call" to '\ue0b0',
        "Call End" to '\ue0b1',
        "Call Made" to '\ue0b2',
        "Call Merge" to '\ue0b3',
        "Call Missed" to '\ue0b4',
        "Call Missed Outgoing" to '\ue0e4',
        "Call Received" to '\ue0b5',
        "Call Split" to '\ue0b6',
        "Call To Action" to '\ue06c',
        "Camera" to '\ue3af',
        "Camera Alt" to '\ue3b0',
        "Camera Enhance" to '\ue8fc',
        "Camera Front" to '\ue3b1',
        "Camera Indoor" to '\uefe9',
        "Camera Outdoor" to '\uefea',
        "Camera Rear" to '\ue3b2',
        "Camera Roll" to '\ue3b3',
        "Cameraswitch" to '\uefeb',
        "Campaign" to '\uef49',
        "Cancel" to '\ue5c9',
        "Cancel Presentation" to '\ue0e9',
        "Cancel Schedule Send" to '\uea39',
        "Candlestick Chart" to '\uead4',
        "Car Crash" to '\uebf2',
        "Car Rental" to '\uea55',
        "Car Repair" to '\uea56',
        "Card Giftcard" to '\ue8f6',
        "Card Membership" to '\ue8f7',
        "Card Travel" to '\ue8f8',
        "Carpenter" to '\uf1f8',
        "Cases" to '\ue992',
        "Casino" to '\ueb40',
        "Cast" to '\ue307',
        "Cast Connected" to '\ue308',
        "Cast For Education" to '\uefec',
        "Castle" to '\ueab1',
        "Catching Pokemon" to '\ue508',
        "Category" to '\ue574',
        "Celebration" to '\uea65',
        "Cell Tower" to '\uebba',
        "Cell Wifi" to '\ue0ec',
        "Center Focus Strong" to '\ue3b4',
        "Center Focus Weak" to '\ue3b5',
        "Chair" to '\uefed',
        "Chair Alt" to '\uefee',
        "Chalet" to '\ue585',
        "Change Circle" to '\ue2e7',
        "Change History" to '\ue86b',
        "Charging Station" to '\uf19d',
        "Chat" to '\ue0b7',
        "Chat Bubble" to '\ue0ca',
        "Chat Bubble Outline" to '\ue0cb',
        "Check" to '\ue5ca',
        "Check Box" to '\ue834',
        "Check Box Outline Blank" to '\ue835',
        "Check Circle" to '\ue86c',
        "Check Circle Outline" to '\ue92d',
        "Checklist" to '\ue6b1',
        "Checklist Rtl" to '\ue6b3',
        "Checkroom" to '\uf19e',
        "Chevron Left" to '\ue5cb',
        "Chevron Right" to '\ue5cc',
        "Child Care" to '\ueb41',
        "Child Friendly" to '\ueb42',
        "Chrome Reader Mode" to '\ue86d',
        "Church" to '\ueaae',
        "Circle" to '\uef4a',
        "Circle Notifications" to '\ue994',
        "Class" to '\ue86e',
        "Clean Hands" to '\uf21f',
        "Cleaning Services" to '\uf0ff',
        "Clear" to '\ue14c',
        "Clear All" to '\ue0b8',
        "Close" to '\ue5cd',
        "Close Fullscreen" to '\uf1cf',
        "Closed Caption" to '\ue01c',
        "Closed Caption Disabled" to '\uf1dc',
        "Closed Caption Off" to '\ue996',
        "Cloud" to '\ue2bd',
        "Cloud Circle" to '\ue2be',
        "Cloud Done" to '\ue2bf',
        "Cloud Download" to '\ue2c0',
        "Cloud Off" to '\ue2c1',
        "Cloud Queue" to '\ue2c2',
        "Cloud Sync" to '\ueb5a',
        "Cloud Upload" to '\ue2c3',
        "Co2" to '\ue7b0',
        "Co Present" to '\ueaf0',
        "Code" to '\ue86f',
        "Code Off" to '\ue4f3',
        "Coffee" to '\uefef',
        "Coffee Maker" to '\ueff0',
        "Collections" to '\ue3b6',
        "Collections Bookmark" to '\ue431',
        "Color Lens" to '\ue3b7',
        "Colorize" to '\ue3b8',
        "Comment" to '\ue0b9',
        "Comment Bank" to '\uea4e',
        "Comments Disabled" to '\ue7a2',
        "Commit" to '\ueaf5',
        "Commute" to '\ue940',
        "Compare" to '\ue3b9',
        "Compare Arrows" to '\ue915',
        "Compass Calibration" to '\ue57c',
        "Compost" to '\ue761',
        "Compress" to '\ue94d',
        "Computer" to '\ue30a',
        "Confirmation Num" to '\ue638',
        "Confirmation Number" to '\ue638',
        "Connect Without Contact" to '\uf223',
        "Connected Tv" to '\ue998',
        "Connecting Airports" to '\ue7c9',
        "Construction" to '\uea3c',
        "Contact Emergency" to '\uf8d1',
        "Contact Mail" to '\ue0d0',
        "Contact Page" to '\uf22e',
        "Contact Phone" to '\ue0cf',
        "Contact Support" to '\ue94c',
        "Contactless" to '\uea71',
        "Contacts" to '\ue0ba',
        "Content Copy" to '\uf08a',
        "Content Cut" to '\uf08b',
        "Content Paste" to '\uf098',
        "Content Paste Go" to '\uea8e',
        "Content Paste Off" to '\ue4f8',
        "Content Paste Search" to '\uea9b',
        "Contrast" to '\ueb37',
        "Control Camera" to '\ue074',
        "Control Point" to '\ue3ba',
        "Control Point Duplicate" to '\ue3bb',
        "Cookie" to '\ueaac',
        "Copy" to '\uf08a',
        "Copy All" to '\ue2ec',
        "Copyright" to '\ue90c',
        "Coronavirus" to '\uf221',
        "Corporate Fare" to '\uf1d0',
        "Cottage" to '\ue587',
        "Countertops" to '\uf1f7',
        "Create" to '\ue150',
        "Create New Folder" to '\ue2cc',
        "Credit Card" to '\ue870',
        "Credit Card Off" to '\ue4f4',
        "Credit Score" to '\ueff1',
        "Crib" to '\ue588',
        "Crisis Alert" to '\uebe9',
        "Crop" to '\ue3be',
        "Crop 16 9" to '\ue3bc',
        "Crop 3 2" to '\ue3bd',
        "Crop 5 4" to '\ue3bf',
        "Crop 7 5" to '\ue3c0',
        "Crop Din" to '\ue3c1',
        "Crop Free" to '\ue3c2',
        "Crop Landscape" to '\ue3c3',
        "Crop Original" to '\ue3c4',
        "Crop Portrait" to '\ue3c5',
        "Crop Rotate" to '\ue437',
        "Crop Square" to '\ue3c6',
        "Cruelty Free" to '\ue799',
        "Css" to '\ueb93',
        "Currency Bitcoin" to '\uebc5',
        "Currency Exchange" to '\ueb70',
        "Currency Franc" to '\ueafa',
        "Currency Lira" to '\ueaef',
        "Currency Pound" to '\ueaf1',
        "Currency Ruble" to '\ueaec',
        "Currency Rupee" to '\ueaf7',
        "Currency Yen" to '\ueafb',
        "Currency Yuan" to '\ueaf9',
        "Curtains" to '\uec1e',
        "Curtains Closed" to '\uec1d',
        "Cut" to '\uf08b',
        "Cyclone" to '\uebd5',
        "Dangerous" to '\ue99a',
        "Dark Mode" to '\ue51c',
        "Dashboard" to '\ue871',
        "Dashboard Customize" to '\ue99b',
        "Data Array" to '\uead1',
        "Data Exploration" to '\ue76f',
        "Data Object" to '\uead3',
        "Data Saver Off" to '\ueff2',
        "Data Saver On" to '\ueff3',
        "Data Thresholding" to '\ueb9f',
        "Data Usage" to '\ue1af',
        "Dataset" to '\uf8ee',
        "Dataset Linked" to '\uf8ef',
        "Date Range" to '\ue916',
        "Deblur" to '\ueb77',
        "Deck" to '\uea42',
        "Dehaze" to '\ue3c7',
        "Delete" to '\ue872',
        "Delete Forever" to '\ue92b',
        "Delete Outline" to '\ue92e',
        "Delete Sweep" to '\ue16c',
        "Delivery Dining" to '\uea72',
        "Density Large" to '\ueba9',
        "Density Medium" to '\ueb9e',
        "Density Small" to '\ueba8',
        "Departure Board" to '\ue576',
        "Description" to '\ue873',
        "Deselect" to '\uebb6',
        "Design Services" to '\uf10a',
        "Desk" to '\uf8f4',
        "Desktop Access Disabled" to '\ue99d',
        "Desktop Mac" to '\ue30b',
        "Desktop Windows" to '\ue30c',
        "Details" to '\ue3c8',
        "Developer Board" to '\ue30d',
        "Developer Board Off" to '\ue4ff',
        "Developer Mode" to '\ue1b0',
        "Device Hub" to '\ue335',
        "Device Thermostat" to '\ue1ff',
        "Device Unknown" to '\ue339',
        "Devices" to '\ue1b1',
        "Devices Fold" to '\uebde',
        "Devices Other" to '\ue337',
        "Dialer Sip" to '\ue0bb',
        "Dialpad" to '\ue0bc',
        "Diamond" to '\uead5',
        "Difference" to '\ueb7d',
        "Dining" to '\ueff4',
        "Dinner Dining" to '\uea57',
        "Directions" to '\ue52e',
        "Directions Bike" to '\ue52f',
        "Directions Boat" to '\ue532',
        "Directions Boat Filled" to '\ueff5',
        "Directions Bus" to '\ue530',
        "Directions Bus Filled" to '\ueff6',
        "Directions Car" to '\ue531',
        "Directions Car Filled" to '\ueff7',
        "Directions Ferry" to '\ue532',
        "Directions Off" to '\uf10f',
        "Directions Railway" to '\ue534',
        "Directions Railway Filled" to '\ueff8',
        "Directions Run" to '\ue566',
        "Directions Subway" to '\ue533',
        "Directions Subway Filled" to '\ueff9',
        "Directions Train" to '\ue534',
        "Directions Transit" to '\ue535',
        "Directions Transit Filled" to '\ueffa',
        "Directions Walk" to '\ue536',
        "Dirty Lens" to '\uef4b',
        "Disabled By Default" to '\uf230',
        "Disabled Visible" to '\ue76e',
        "Disc Full" to '\ue610',
        "Discord" to '\uea6c',
        "Discount" to '\uebc9',
        "Display Settings" to '\ueb97',
        "Diversity 1" to '\uf8d7',
        "Diversity 2" to '\uf8d8',
        "Diversity 3" to '\uf8d9',
        "Dnd Forwardslash" to '\ue611',
        "Dns" to '\ue875',
        "Do Disturb" to '\uf08c',
        "Do Disturb Alt" to '\uf08d',
        "Do Disturb Off" to '\uf08e',
        "Do Disturb On" to '\uf08f',
        "Do Not Disturb" to '\ue612',
        "Do Not Disturb Alt" to '\ue611',
        "Do Not Disturb Off" to '\ue643',
        "Do Not Disturb On" to '\ue644',
        "Do Not Disturb On Total Silence" to '\ueffb',
        "Do Not Step" to '\uf19f',
        "Do Not Touch" to '\uf1b0',
        "Dock" to '\ue30e',
        "Document Scanner" to '\ue5fa',
        "Domain" to '\ue7ee',
        "Domain Add" to '\ueb62',
        "Domain Disabled" to '\ue0ef',
        "Domain Verification" to '\uef4c',
        "Done" to '\ue876',
        "Done All" to '\ue877',
        "Done Outline" to '\ue92f',
        "Donut Large" to '\ue917',
        "Donut Small" to '\ue918',
        "Door Back" to '\ueffc',
        "Door Front" to '\ueffd',
        "Door Sliding" to '\ueffe',
        "Doorbell" to '\uefff',
        "Double Arrow" to '\uea50',
        "Downhill Skiing" to '\ue509',
        "Download" to '\uf090',
        "Download Done" to '\uf091',
        "Download For Offline" to '\uf000',
        "Downloading" to '\uf001',
        "Drafts" to '\ue151',
        "Drag Handle" to '\ue25d',
        "Drag Indicator" to '\ue945',
        "Draw" to '\ue746',
        "Drive Eta" to '\ue613',
        "Drive File Move" to '\ue675',
        "Drive File Move Rtl" to '\ue76d',
        "Drive File Rename Outline" to '\ue9a2',
        "Drive Folder Upload" to '\ue9a3',
        "Dry" to '\uf1b3',
        "Dry Cleaning" to '\uea58',
        "Duo" to '\ue9a5',
        "Dvr" to '\ue1b2',
        "Dynamic Feed" to '\uea14',
        "Dynamic Form" to '\uf1bf',
        "E Mobiledata" to '\uf002',
        "Earbuds" to '\uf003',
        "Earbuds Battery" to '\uf004',
        "East" to '\uf1df',
        "Eco" to '\uea35',
        "Edgesensor High" to '\uf005',
        "Edgesensor Low" to '\uf006',
        "Edit" to '\ue3c9',
        "Edit Attributes" to '\ue578',
        "Edit Calendar" to '\ue742',
        "Edit Location" to '\ue568',
        "Edit Location Alt" to '\ue1c5',
        "Edit Note" to '\ue745',
        "Edit Notifications" to '\ue525',
        "Edit Off" to '\ue950',
        "Edit Road" to '\uef4d',
        "Egg" to '\ueacc',
        "Egg Alt" to '\ueac8',
        "Eject" to '\ue8fb',
        "Elderly" to '\uf21a',
        "Elderly Woman" to '\ueb69',
        "Electric Bike" to '\ueb1b',
        "Electric Bolt" to '\uec1c',
        "Electric Car" to '\ueb1c',
        "Electric Meter" to '\uec1b',
        "Electric Moped" to '\ueb1d',
        "Electric Rickshaw" to '\ueb1e',
        "Electric Scooter" to '\ueb1f',
        "Electrical Services" to '\uf102',
        "Elevator" to '\uf1a0',
        "Email" to '\ue0be',
        "Emergency" to '\ue1eb',
        "Emergency Recording" to '\uebf4',
        "Emergency Share" to '\uebf6',
        "Emoji Emotions" to '\uea22',
        "Emoji Events" to '\uea23',
        "Emoji Flags" to '\uea1a',
        "Emoji Food Beverage" to '\uea1b',
        "Emoji Nature" to '\uea1c',
        "Emoji Objects" to '\uea24',
        "Emoji People" to '\uea1d',
        "Emoji Symbols" to '\uea1e',
        "Emoji Transportation" to '\uea1f',
        "Energy Savings Leaf" to '\uec1a',
        "Engineering" to '\uea3d',
        "Enhance Photo Translate" to '\ue8fc',
        "Enhanced Encryption" to '\ue63f',
        "Equalizer" to '\ue01d',
        "Error" to '\ue000',
        "Error Outline" to '\ue001',
        "Escalator" to '\uf1a1',
        "Escalator Warning" to '\uf1ac',
        "Euro" to '\uea15',
        "Euro Symbol" to '\ue926',
        "Ev Station" to '\ue56d',
        "Event" to '\ue878',
        "Event Available" to '\ue614',
        "Event Busy" to '\ue615',
        "Event Note" to '\ue616',
        "Event Repeat" to '\ueb7b',
        "Event Seat" to '\ue903',
        "Exit To App" to '\ue879',
        "Expand" to '\ue94f',
        "Expand Circle Down" to '\ue7cd',
        "Expand Less" to '\ue5ce',
        "Expand More" to '\ue5cf',
        "Explicit" to '\ue01e',
        "Explore" to '\ue87a',
        "Explore Off" to '\ue9a8',
        "Exposure" to '\ue3ca',
        "Exposure Minus 1" to '\ue3cb',
        "Exposure Minus 2" to '\ue3cc',
        "Exposure Neg 1" to '\ue3cb',
        "Exposure Neg 2" to '\ue3cc',
        "Exposure Plus 1" to '\ue3cd',
        "Exposure Plus 2" to '\ue3ce',
        "Exposure Zero" to '\ue3cf',
        "Extension" to '\ue87b',
        "Extension Off" to '\ue4f5',
        "Face" to '\ue87c',
        "Face 2" to '\uf8da',
        "Face 3" to '\uf8db',
        "Face 4" to '\uf8dc',
        "Face 5" to '\uf8dd',
        "Face 6" to '\uf8de',
        "Face Retouching Natural" to '\uef4e',
        "Face Retouching Off" to '\uf007',
        "Face Unlock" to '\uf008',
        "Facebook" to '\uf234',
        "Fact Check" to '\uf0c5',
        "Factory" to '\uebbc',
        "Family Restroom" to '\uf1a2',
        "Fast Forward" to '\ue01f',
        "Fast Rewind" to '\ue020',
        "Fastfood" to '\ue57a',
        "Favorite" to '\ue87d',
        "Favorite Border" to '\ue87e',
        "Favorite Outline" to '\ue87e',
        "Fax" to '\uead8',
        "Featured Play List" to '\ue06d',
        "Featured Video" to '\ue06e',
        "Feed" to '\uf009',
        "Feedback" to '\ue87f',
        "Female" to '\ue590',
        "Fence" to '\uf1f6',
        "Festival" to '\uea68',
        "Fiber Dvr" to '\ue05d',
        "Fiber Manual Record" to '\ue061',
        "Fiber New" to '\ue05e',
        "Fiber Pin" to '\ue06a',
        "Fiber Smart Record" to '\ue062',
        "File Copy" to '\ue173',
        "File Download" to '\ue2c4',
        "File Download Done" to '\ue9aa',
        "File Download Off" to '\ue4fe',
        "File Open" to '\ueaf3',
        "File Present" to '\uea0e',
        "File Upload" to '\ue2c6',
        "Filter" to '\ue3d3',
        "Filter 1" to '\ue3d0',
        "Filter 2" to '\ue3d1',
        "Filter 3" to '\ue3d2',
        "Filter 4" to '\ue3d4',
        "Filter 5" to '\ue3d5',
        "Filter 6" to '\ue3d6',
        "Filter 7" to '\ue3d7',
        "Filter 8" to '\ue3d8',
        "Filter 9" to '\ue3d9',
        "Filter 9 Plus" to '\ue3da',
        "Filter Alt" to '\uef4f',
        "Filter Alt Off" to '\ueb32',
        "Filter B And W" to '\ue3db',
        "Filter Center Focus" to '\ue3dc',
        "Filter Drama" to '\ue3dd',
        "Filter Frames" to '\ue3de',
        "Filter Hdr" to '\ue3df',
        "Filter List" to '\ue152',
        "Filter List Off" to '\ueb57',
        "Filter None" to '\ue3e0',
        "Filter Tilt Shift" to '\ue3e2',
        "Filter Vintage" to '\ue3e3',
        "Find In Page" to '\ue880',
        "Find Replace" to '\ue881',
        "Fingerprint" to '\ue90d',
        "Fire Extinguisher" to '\uf1d8',
        "Fire Hydrant Alt" to '\uf8f1',
        "Fire Truck" to '\uf8f2',
        "Fireplace" to '\uea43',
        "First Page" to '\ue5dc',
        "Fit Screen" to '\uea10',
        "Fitbit" to '\ue82b',
        "Fitness Center" to '\ueb43',
        "Flag" to '\ue153',
        "Flag Circle" to '\ueaf8',
        "Flaky" to '\uef50',
        "Flare" to '\ue3e4',
        "Flash Auto" to '\ue3e5',
        "Flash Off" to '\ue3e6',
        "Flash On" to '\ue3e7',
        "Flashlight Off" to '\uf00a',
        "Flashlight On" to '\uf00b',
        "Flatware" to '\uf00c',
        "Flight" to '\ue539',
        "Flight Class" to '\ue7cb',
        "Flight Land" to '\ue904',
        "Flight Takeoff" to '\ue905',
        "Flip" to '\ue3e8',
        "Flip Camera Android" to '\uea37',
        "Flip Camera Ios" to '\uea38',
        "Flip To Back" to '\ue882',
        "Flip To Front" to '\ue883',
        "Flood" to '\uebe6',
        "Flourescent" to '\uf00d',
        "Fluorescent" to '\uf00d',
        "Flutter Dash" to '\ue00b',
        "Fmd Bad" to '\uf00e',
        "Fmd Good" to '\uf00f',
        "Folder" to '\ue2c7',
        "Folder Copy" to '\uebbd',
        "Folder Delete" to '\ueb34',
        "Folder Off" to '\ueb83',
        "Folder Open" to '\ue2c8',
        "Folder Shared" to '\ue2c9',
        "Folder Special" to '\ue617',
        "Folder Zip" to '\ueb2c',
        "Follow The Signs" to '\uf222',
        "Font Download" to '\ue167',
        "Font Download Off" to '\ue4f9',
        "Food Bank" to '\uf1f2',
        "Forest" to '\uea99',
        "Fork Left" to '\ueba0',
        "Fork Right" to '\uebac',
        "Format Align Center" to '\ue234',
        "Format Align Justify" to '\ue235',
        "Format Align Left" to '\ue236',
        "Format Align Right" to '\ue237',
        "Format Bold" to '\ue238',
        "Format Clear" to '\ue239',
        "Format Color Fill" to '\ue23a',
        "Format Color Reset" to '\ue23b',
        "Format Color Text" to '\ue23c',
        "Format Indent Decrease" to '\ue23d',
        "Format Indent Increase" to '\ue23e',
        "Format Italic" to '\ue23f',
        "Format Line Spacing" to '\ue240',
        "Format List Bulleted" to '\ue241',
        "Format List Numbered" to '\ue242',
        "Format List Numbered Rtl" to '\ue267',
        "Format Overline" to '\ueb65',
        "Format Paint" to '\ue243',
        "Format Quote" to '\ue244',
        "Format Shapes" to '\ue25e',
        "Format Size" to '\ue245',
        "Format Strikethrough" to '\ue246',
        "Format Textdirection L To R" to '\ue247',
        "Format Textdirection R To L" to '\ue248',
        "Format Underline" to '\ue765',
        "Format Underlined" to '\ue765',
        "Fort" to '\ueaad',
        "Forum" to '\ue0bf',
        "Forward" to '\ue154',
        "Forward 10" to '\ue056',
        "Forward 30" to '\ue057',
        "Forward 5" to '\ue058',
        "Forward To Inbox" to '\uf187',
        "Foundation" to '\uf200',
        "Free Breakfast" to '\ueb44',
        "Free Cancellation" to '\ue748',
        "Front Hand" to '\ue769',
        "Fullscreen" to '\ue5d0',
        "Fullscreen Exit" to '\ue5d1',
        "Functions" to '\ue24a',
        "G Mobiledata" to '\uf010',
        "G Translate" to '\ue927',
        "Gamepad" to '\ue30f',
        "Games" to '\ue021',
        "Garage" to '\uf011',
        "Gas Meter" to '\uec19',
        "Gavel" to '\ue90e',
        "Generating Tokens" to '\ue749',
        "Gesture" to '\ue155',
        "Get App" to '\ue884',
        "Gif" to '\ue908',
        "Gif Box" to '\ue7a3',
        "Girl" to '\ueb68',
        "Gite" to '\ue58b',
        "Golf Course" to '\ueb45',
        "Gpp Bad" to '\uf012',
        "Gpp Good" to '\uf013',
        "Gpp Maybe" to '\uf014',
        "Gps Fixed" to '\ue1b3',
        "Gps Not Fixed" to '\ue1b4',
        "Gps Off" to '\ue1b5',
        "Grade" to '\ue885',
        "Gradient" to '\ue3e9',
        "Grading" to '\uea4f',
        "Grain" to '\ue3ea',
        "Graphic Eq" to '\ue1b8',
        "Grass" to '\uf205',
        "Grid 3X3" to '\uf015',
        "Grid 4X4" to '\uf016',
        "Grid Goldenratio" to '\uf017',
        "Grid Off" to '\ue3eb',
        "Grid On" to '\ue3ec',
        "Grid View" to '\ue9b0',
        "Group" to '\ue7ef',
        "Group Add" to '\ue7f0',
        "Group Off" to '\ue747',
        "Group Remove" to '\ue7ad',
        "Group Work" to '\ue886',
        "Groups" to '\uf233',
        "Groups 2" to '\uf8df',
        "Groups 3" to '\uf8e0',
        "H Mobiledata" to '\uf018',
        "H Plus Mobiledata" to '\uf019',
        "Hail" to '\ue9b1',
        "Handshake" to '\uebcb',
        "Handyman" to '\uf10b',
        "Hardware" to '\uea59',
        "Hd" to '\ue052',
        "Hdr Auto" to '\uf01a',
        "Hdr Auto Select" to '\uf01b',
        "Hdr Enhanced Select" to '\uef51',
        "Hdr Off" to '\ue3ed',
        "Hdr Off Select" to '\uf01c',
        "Hdr On" to '\ue3ee',
        "Hdr On Select" to '\uf01d',
        "Hdr Plus" to '\uf01e',
        "Hdr Strong" to '\ue3f1',
        "Hdr Weak" to '\ue3f2',
        "Headphones" to '\uf01f',
        "Headphones Battery" to '\uf020',
        "Headset" to '\ue310',
        "Headset Mic" to '\ue311',
        "Headset Off" to '\ue33a',
        "Healing" to '\ue3f3',
        "Health And Safety" to '\ue1d5',
        "Hearing" to '\ue023',
        "Hearing Disabled" to '\uf104',
        "Heart Broken" to '\ueac2',
        "Heat Pump" to '\uec18',
        "Height" to '\uea16',
        "Help" to '\ue887',
        "Help Center" to '\uf1c0',
        "Help Outline" to '\ue8fd',
        "Hevc" to '\uf021',
        "Hexagon" to '\ueb39',
        "Hide Image" to '\uf022',
        "Hide Source" to '\uf023',
        "High Quality" to '\ue024',
        "Highlight" to '\ue25f',
        "Highlight Alt" to '\uef52',
        "Highlight Off" to '\ue888',
        "Highlight Remove" to '\ue888',
        "Hiking" to '\ue50a',
        "History" to '\ue889',
        "History Edu" to '\uea3e',
        "History Toggle Off" to '\uf17d',
        "Hive" to '\ueaa6',
        "Hls" to '\ueb8a',
        "Hls Off" to '\ueb8c',
        "Holiday Village" to '\ue58a',
        "Home" to '\ue88a',
        "Home Max" to '\uf024',
        "Home Mini" to '\uf025',
        "Home Repair Service" to '\uf100',
        "Home Work" to '\uea09',
        "Horizontal Distribute" to '\ue014',
        "Horizontal Rule" to '\uf108',
        "Horizontal Split" to '\ue947',
        "Hot Tub" to '\ueb46',
        "Hotel" to '\ue53a',
        "Hotel Class" to '\ue743',
        "Hourglass Bottom" to '\uea5c',
        "Hourglass Disabled" to '\uef53',
        "Hourglass Empty" to '\ue88b',
        "Hourglass Full" to '\ue88c',
        "Hourglass Top" to '\uea5b',
        "House" to '\uea44',
        "House Siding" to '\uf202',
        "Houseboat" to '\ue584',
        "How To Reg" to '\ue174',
        "How To Vote" to '\ue175',
        "Html" to '\ueb7e',
        "Http" to '\ue902',
        "Https" to '\ue88d',
        "Hub" to '\ue9f4',
        "Hvac" to '\uf10e',
        "Ice Skating" to '\ue50b',
        "Icecream" to '\uea69',
        "Image" to '\ue3f4',
        "Image Aspect Ratio" to '\ue3f5',
        "Image Not Supported" to '\uf116',
        "Image Search" to '\ue43f',
        "Imagesearch Roller" to '\ue9b4',
        "Import Contacts" to '\ue0e0',
        "Import Export" to '\ue0c3',
        "Important Devices" to '\ue912',
        "Inbox" to '\ue156',
        "Incomplete Circle" to '\ue79b',
        "Indeterminate Check Box" to '\ue909',
        "Info" to '\ue88e',
        "Info Outline" to '\ue88f',
        "Input" to '\ue890',
        "Insert Chart" to '\ue24b',
        "Insert Chart Outlined" to '\ue26a',
        "Insert Comment" to '\ue24c',
        "Insert Drive File" to '\ue24d',
        "Insert Emoticon" to '\ue24e',
        "Insert Invitation" to '\ue24f',
        "Insert Link" to '\ue250',
        "Insert Page Break" to '\ueaca',
        "Insert Photo" to '\ue251',
        "Insights" to '\uf092',
        "Install Desktop" to '\ueb71',
        "Install Mobile" to '\ueb72',
        "Integration Instructions" to '\uef54',
        "Interests" to '\ue7c8',
        "Interpreter Mode" to '\ue83b',
        "Inventory" to '\ue179',
        "Inventory 2" to '\ue1a1',
        "Invert Colors" to '\ue891',
        "Invert Colors Off" to '\ue0c4',
        "Invert Colors On" to '\ue891',
        "Ios Share" to '\ue6b8',
        "Iron" to '\ue583',
        "Iso" to '\ue3f6',
        "Javascript" to '\ueb7c',
        "Join Full" to '\ueaeb',
        "Join Inner" to '\ueaf4',
        "Join Left" to '\ueaf2',
        "Join Right" to '\ueaea',
        "Kayaking" to '\ue50c',
        "Kebab Dining" to '\ue842',
        "Key" to '\ue73c',
        "Key Off" to '\ueb84',
        "Keyboard" to '\ue312',
        "Keyboard Alt" to '\uf028',
        "Keyboard Arrow Down" to '\ue313',
        "Keyboard Arrow Left" to '\ue314',
        "Keyboard Arrow Right" to '\ue315',
        "Keyboard Arrow Up" to '\ue316',
        "Keyboard Backspace" to '\ue317',
        "Keyboard Capslock" to '\ue318',
        "Keyboard Command Key" to '\ueae7',
        "Keyboard Control" to '\ueae1',
        "Keyboard Control Key" to '\ueae6',
        "Keyboard Double Arrow Down" to '\uead0',
        "Keyboard Double Arrow Left" to '\ueac3',
        "Keyboard Double Arrow Right" to '\ueac9',
        "Keyboard Double Arrow Up" to '\ueacf',
        "Keyboard Hide" to '\ue31a',
        "Keyboard Option Key" to '\ueae8',
        "Keyboard Return" to '\ue31b',
        "Keyboard Tab" to '\ue31c',
        "Keyboard Voice" to '\ue31d',
        "King Bed" to '\uea45',
        "Kitchen" to '\ueb47',
        "Kitesurfing" to '\ue50d',
        "Label" to '\ue892',
        "Label Important" to '\ue937',
        "Label Important Outline" to '\ue948',
        "Label Off" to '\ue9b6',
        "Label Outline" to '\ue893',
        "Lan" to '\ueb2f',
        "Landscape" to '\ue3f7',
        "Landslide" to '\uebd7',
        "Language" to '\ue894',
        "Laptop" to '\ue31e',
        "Laptop Chromebook" to '\ue31f',
        "Laptop Mac" to '\ue320',
        "Laptop Windows" to '\ue321',
        "Last Page" to '\ue5dd',
        "Launch" to '\ue895',
        "Layers" to '\ue53b',
        "Layers Clear" to '\ue53c',
        "Leaderboard" to '\uf20c',
        "Leak Add" to '\ue3f8',
        "Leak Remove" to '\ue3f9',
        "Leave Bags At Home" to '\uf23b',
        "Legend Toggle" to '\uf11b',
        "Lens" to '\ue3fa',
        "Lens Blur" to '\uf029',
        "Library Add" to '\ue02e',
        "Library Add Check" to '\ue9b7',
        "Library Books" to '\ue02f',
        "Library Music" to '\ue030',
        "Light" to '\uf02a',
        "Light Mode" to '\ue518',
        "Lightbulb" to '\ue0f0',
        "Lightbulb Circle" to '\uebfe',
        "Lightbulb Outline" to '\ue90f',
        "Line Axis" to '\uea9a',
        "Line Style" to '\ue919',
        "Line Weight" to '\ue91a',
        "Linear Scale" to '\ue260',
        "Link" to '\ue157',
        "Link Off" to '\ue16f',
        "Linked Camera" to '\ue438',
        "Liquor" to '\uea60',
        "List" to '\ue896',
        "List Alt" to '\ue0ee',
        "Live Help" to '\ue0c6',
        "Live Tv" to '\ue639',
        "Living" to '\uf02b',
        "Local Activity" to '\ue53f',
        "Local Airport" to '\ue53d',
        "Local Atm" to '\ue53e',
        "Local Attraction" to '\ue53f',
        "Local Bar" to '\ue540',
        "Local Cafe" to '\ue541',
        "Local Car Wash" to '\ue542',
        "Local Convenience Store" to '\ue543',
        "Local Dining" to '\ue556',
        "Local Drink" to '\ue544',
        "Local Fire Department" to '\uef55',
        "Local Florist" to '\ue545',
        "Local Gas Station" to '\ue546',
        "Local Grocery Store" to '\ue547',
        "Local Hospital" to '\ue548',
        "Local Hotel" to '\ue549',
        "Local Laundry Service" to '\ue54a',
        "Local Library" to '\ue54b',
        "Local Mall" to '\ue54c',
        "Local Movies" to '\ue54d',
        "Local Offer" to '\ue54e',
        "Local Parking" to '\ue54f',
        "Local Pharmacy" to '\ue550',
        "Local Phone" to '\ue551',
        "Local Pizza" to '\ue552',
        "Local Play" to '\ue553',
        "Local Police" to '\uef56',
        "Local Post Office" to '\ue554',
        "Local Print Shop" to '\ue555',
        "Local Printshop" to '\ue555',
        "Local Restaurant" to '\ue556',
        "Local See" to '\ue557',
        "Local Shipping" to '\ue558',
        "Local Taxi" to '\ue559',
        "Location City" to '\ue7f1',
        "Location Disabled" to '\ue1b6',
        "Location History" to '\ue55a',
        "Location Off" to '\ue0c7',
        "Location On" to '\ue0c8',
        "Location Searching" to '\ue1b7',
        "Lock" to '\ue897',
        "Lock Clock" to '\uef57',
        "Lock Open" to '\ue898',
        "Lock Outline" to '\ue899',
        "Lock Person" to '\uf8f3',
        "Lock Reset" to '\ueade',
        "Login" to '\uea77',
        "Logo Dev" to '\uead6',
        "Logout" to '\ue9ba',
        "Looks" to '\ue3fc',
        "Looks 3" to '\ue3fb',
        "Looks 4" to '\ue3fd',
        "Looks 5" to '\ue3fe',
        "Looks 6" to '\ue3ff',
        "Looks One" to '\ue400',
        "Looks Two" to '\ue401',
        "Loop" to '\ue028',
        "Loupe" to '\ue402',
        "Low Priority" to '\ue16d',
        "Loyalty" to '\ue89a',
        "Lte Mobiledata" to '\uf02c',
        "Lte Plus Mobiledata" to '\uf02d',
        "Luggage" to '\uf235',
        "Lunch Dining" to '\uea61',
        "Lyrics" to '\uec0b',
        "Macro Off" to '\uf8d2',
        "Mail" to '\ue158',
        "Mail Lock" to '\uec0a',
        "Mail Outline" to '\ue0e1',
        "Male" to '\ue58e',
        "Man" to '\ue4eb',
        "Man 2" to '\uf8e1',
        "Man 3" to '\uf8e2',
        "Man 4" to '\uf8e3',
        "Manage Accounts" to '\uf02e',
        "Manage History" to '\uebe7',
        "Manage Search" to '\uf02f',
        "Map" to '\ue55b',
        "Maps Home Work" to '\uf030',
        "Maps Ugc" to '\uef58',
        "Margin" to '\ue9bb',
        "Mark As Unread" to '\ue9bc',
        "Mark Chat Read" to '\uf18b',
        "Mark Chat Unread" to '\uf189',
        "Mark Email Read" to '\uf18c',
        "Mark Email Unread" to '\uf18a',
        "Mark Unread Chat Alt" to '\ueb9d',
        "Markunread" to '\ue159',
        "Markunread Mailbox" to '\ue89b',
        "Masks" to '\uf218',
        "Maximize" to '\ue930',
        "Media Bluetooth Off" to '\uf031',
        "Media Bluetooth On" to '\uf032',
        "Mediation" to '\uefa7',
        "Medical Information" to '\uebed',
        "Medical Services" to '\uf109',
        "Medication" to '\uf033',
        "Medication Liquid" to '\uea87',
        "Meeting Room" to '\ueb4f',
        "Memory" to '\ue322',
        "Menu" to '\ue5d2',
        "Menu Book" to '\uea19',
        "Menu Open" to '\ue9bd',
        "Merge" to '\ueb98',
        "Merge Type" to '\ue252',
        "Message" to '\ue0c9',
        "Messenger" to '\ue0ca',
        "Messenger Outline" to '\ue0cb',
        "Mic" to '\ue029',
        "Mic External Off" to '\uef59',
        "Mic External On" to '\uef5a',
        "Mic None" to '\ue02a',
        "Mic Off" to '\ue02b',
        "Microwave" to '\uf204',
        "Military Tech" to '\uea3f',
        "Minimize" to '\ue931',
        "Minor Crash" to '\uebf1',
        "Miscellaneous Services" to '\uf10c',
        "Missed Video Call" to '\ue073',
        "Mms" to '\ue618',
        "Mobile Friendly" to '\ue200',
        "Mobile Off" to '\ue201',
        "Mobile Screen Share" to '\ue0e7',
        "Mobiledata Off" to '\uf034',
        "Mode" to '\uf097',
        "Mode Comment" to '\ue253',
        "Mode Edit" to '\ue254',
        "Mode Edit Outline" to '\uf035',
        "Mode Fan Off" to '\uec17',
        "Mode Night" to '\uf036',
        "Mode Of Travel" to '\ue7ce',
        "Mode Standby" to '\uf037',
        "Model Training" to '\uf0cf',
        "Monetization On" to '\ue263',
        "Money" to '\ue57d',
        "Money Off" to '\ue25c',
        "Money Off Csred" to '\uf038',
        "Monitor" to '\uef5b',
        "Monitor Heart" to '\ueaa2',
        "Monitor Weight" to '\uf039',
        "Monochrome Photos" to '\ue403',
        "Mood" to '\ue7f2',
        "Mood Bad" to '\ue7f3',
        "Moped" to '\ueb28',
        "More" to '\ue619',
        "More Horiz" to '\ueae1',
        "More Time" to '\uea5d',
        "More Vert" to '\ue5d4',
        "Mosque" to '\ueab2',
        "Motion Photos Auto" to '\uf03a',
        "Motion Photos Off" to '\ue9c0',
        "Motion Photos On" to '\ue9c1',
        "Motion Photos Pause" to '\uf227',
        "Motion Photos Paused" to '\ue9c2',
        "Motorcycle" to '\ue91b',
        "Mouse" to '\ue323',
        "Move Down" to '\ueb61',
        "Move To Inbox" to '\ue168',
        "Move Up" to '\ueb64',
        "Movie" to '\ue02c',
        "Movie Creation" to '\ue404',
        "Movie Filter" to '\ue43a',
        "Moving" to '\ue501',
        "Mp" to '\ue9c3',
        "Multiline Chart" to '\ue6df',
        "Multiple Stop" to '\uf1b9',
        "Multitrack Audio" to '\ue1b8',
        "Museum" to '\uea36',
        "Music Note" to '\ue405',
        "Music Off" to '\ue440',
        "Music Video" to '\ue063',
        "My Library Add" to '\ue02e',
        "My Library Books" to '\ue02f',
        "My Library Music" to '\ue030',
        "My Location" to '\ue55c',
        "Nat" to '\uef5c',
        "Nature" to '\ue406',
        "Nature People" to '\ue407',
        "Navigate Before" to '\ue408',
        "Navigate Next" to '\ue409',
        "Navigation" to '\ue55d',
        "Near Me" to '\ue569',
        "Near Me Disabled" to '\uf1ef',
        "Nearby Error" to '\uf03b',
        "Nearby Off" to '\uf03c',
        "Nest Cam Wired Stand" to '\uec16',
        "Network Cell" to '\ue1b9',
        "Network Check" to '\ue640',
        "Network Locked" to '\ue61a',
        "Network Ping" to '\uebca',
        "Network Wifi" to '\ue1ba',
        "Network Wifi 1 Bar" to '\uebe4',
        "Network Wifi 2 Bar" to '\uebd6',
        "Network Wifi 3 Bar" to '\uebe1',
        "New Label" to '\ue609',
        "New Releases" to '\ue031',
        "Newspaper" to '\ueb81',
        "Next Plan" to '\uef5d',
        "Next Week" to '\ue16a',
        "Nfc" to '\ue1bb',
        "Night Shelter" to '\uf1f1',
        "Nightlife" to '\uea62',
        "Nightlight" to '\uf03d',
        "Nightlight Round" to '\uef5e',
        "Nights Stay" to '\uea46',
        "No Accounts" to '\uf03e',
        "No Adult Content" to '\uf8fe',
        "No Backpack" to '\uf237',
        "No Cell" to '\uf1a4',
        "No Crash" to '\uebf0',
        "No Drinks" to '\uf1a5',
        "No Encryption" to '\ue641',
        "No Encryption Gmailerrorred" to '\uf03f',
        "No Flash" to '\uf1a6',
        "No Food" to '\uf1a7',
        "No Luggage" to '\uf23b',
        "No Meals" to '\uf1d6',
        "No Meeting Room" to '\ueb4e',
        "No Photography" to '\uf1a8',
        "No Sim" to '\ue0cc',
        "No Stroller" to '\uf1af',
        "No Transfer" to '\uf1d5',
        "Noise Aware" to '\uebec',
        "Noise Control Off" to '\uebf3',
        "Nordic Walking" to '\ue50e',
        "North" to '\uf1e0',
        "North East" to '\uf1e1',
        "North West" to '\uf1e2',
        "Not Accessible" to '\uf0fe',
        "Not Interested" to '\ue033',
        "Not Listed Location" to '\ue575',
        "Not Started" to '\uf0d1',
        "Note" to '\ue06f',
        "Note Add" to '\ue89c',
        "Note Alt" to '\uf040',
        "Notes" to '\ue26c',
        "Notification Add" to '\ue399',
        "Notification Important" to '\ue004',
        "Notifications" to '\ue7f4',
        "Notifications Active" to '\ue7f7',
        "Notifications None" to '\ue7f5',
        "Notifications Off" to '\ue7f6',
        "Notifications On" to '\ue7f7',
        "Notifications Paused" to '\ue7f8',
        "Now Wallpaper" to '\ue75f',
        "Now Widgets" to '\ue75e',
        "Numbers" to '\ueac7',
        "Offline Bolt" to '\ue932',
        "Offline Pin" to '\ue90a',
        "Offline Share" to '\ue9c5',
        "Oil Barrel" to '\uec15',
        "On Device Training" to '\uebfd',
        "Ondemand Video" to '\ue63a',
        "Online Prediction" to '\uf0eb',
        "Opacity" to '\ue91c',
        "Open In Browser" to '\ue89d',
        "Open In Full" to '\uf1ce',
        "Open In New" to '\ue89e',
        "Open In New Off" to '\ue4f6',
        "Open With" to '\ue89f',
        "Other Houses" to '\ue58c',
        "Outbond" to '\uf228',
        "Outbound" to '\ue1ca',
        "Outbox" to '\uef5f',
        "Outdoor Grill" to '\uea47',
        "Outlet" to '\uf1d4',
        "Outlined Flag" to '\ue16e',
        "Output" to '\uebbe',
        "Padding" to '\ue9c8',
        "Pages" to '\ue7f9',
        "Pageview" to '\ue8a0',
        "Paid" to '\uf041',
        "Palette" to '\ue40a',
        "Pan Tool" to '\ue925',
        "Pan Tool Alt" to '\uebb9',
        "Panorama" to '\ue40b',
        "Panorama Fish Eye" to '\ue40c',
        "Panorama Fisheye" to '\ue40c',
        "Panorama Horizontal" to '\ue40d',
        "Panorama Horizontal Select" to '\uef60',
        "Panorama Photosphere" to '\ue9c9',
        "Panorama Photosphere Select" to '\ue9ca',
        "Panorama Vertical" to '\ue40e',
        "Panorama Vertical Select" to '\uef61',
        "Panorama Wide Angle" to '\ue40f',
        "Panorama Wide Angle Select" to '\uef62',
        "Paragliding" to '\ue50f',
        "Park" to '\uea63',
        "Party Mode" to '\ue7fa',
        "Password" to '\uf042',
        "Paste" to '\uf098',
        "Pattern" to '\uf043',
        "Pause" to '\ue034',
        "Pause Circle" to '\ue1a2',
        "Pause Circle Filled" to '\ue035',
        "Pause Circle Outline" to '\ue036',
        "Pause Presentation" to '\ue0ea',
        "Payment" to '\ue8a1',
        "Payments" to '\uef63',
        "Paypal" to '\uea8d',
        "Pedal Bike" to '\ueb29',
        "Pending" to '\uef64',
        "Pending Actions" to '\uf1bb',
        "Pentagon" to '\ueb50',
        "People" to '\ue7fb',
        "People Alt" to '\uea21',
        "People Outline" to '\ue7fc',
        "Percent" to '\ueb58',
        "Perm Camera Mic" to '\ue8a2',
        "Perm Contact Cal" to '\ue8a3',
        "Perm Contact Calendar" to '\ue8a3',
        "Perm Data Setting" to '\ue8a4',
        "Perm Device Info" to '\ue8a5',
        "Perm Device Information" to '\ue8a5',
        "Perm Identity" to '\ue8a6',
        "Perm Media" to '\ue8a7',
        "Perm Phone Msg" to '\ue8a8',
        "Perm Scan Wifi" to '\ue8a9',
        "Person" to '\ue7fd',
        "Person 2" to '\uf8e4',
        "Person 3" to '\uf8e5',
        "Person 4" to '\uf8e6',
        "Person Add" to '\ue7fe',
        "Person Add Alt" to '\uea4d',
        "Person Add Alt 1" to '\uef65',
        "Person Add Disabled" to '\ue9cb',
        "Person Off" to '\ue510',
        "Person Outline" to '\ue7ff',
        "Person Pin" to '\ue55a',
        "Person Pin Circle" to '\ue56a',
        "Person Remove" to '\uef66',
        "Person Remove Alt 1" to '\uef67',
        "Person Search" to '\uf106',
        "Personal Injury" to '\ue6da',
        "Personal Video" to '\ue63b',
        "Pest Control" to '\uf0fa',
        "Pest Control Rodent" to '\uf0fd',
        "Pets" to '\ue91d',
        "Phishing" to '\uead7',
        "Phone" to '\ue0cd',
        "Phone Android" to '\ue324',
        "Phone Bluetooth Speaker" to '\ue61b',
        "Phone Callback" to '\ue649',
        "Phone Disabled" to '\ue9cc',
        "Phone Enabled" to '\ue9cd',
        "Phone Forwarded" to '\ue61c',
        "Phone In Talk" to '\ue61d',
        "Phone Iphone" to '\ue325',
        "Phone Locked" to '\ue61e',
        "Phone Missed" to '\ue61f',
        "Phone Paused" to '\ue620',
        "Phonelink" to '\ue326',
        "Phonelink Erase" to '\ue0db',
        "Phonelink Lock" to '\ue0dc',
        "Phonelink Off" to '\ue327',
        "Phonelink Ring" to '\ue0dd',
        "Phonelink Setup" to '\ue0de',
        "Photo" to '\ue410',
        "Photo Album" to '\ue411',
        "Photo Camera" to '\ue412',
        "Photo Camera Back" to '\uef68',
        "Photo Camera Front" to '\uef69',
        "Photo Filter" to '\ue43b',
        "Photo Library" to '\ue413',
        "Photo Size Select Actual" to '\ue432',
        "Photo Size Select Large" to '\ue433',
        "Photo Size Select Small" to '\ue434',
        "Php" to '\ueb8f',
        "Piano" to '\ue521',
        "Piano Off" to '\ue520',
        "Picture As Pdf" to '\ue415',
        "Picture In Picture" to '\ue8aa',
        "Picture In Picture Alt" to '\ue911',
        "Pie Chart" to '\ue6c4',
        "Pie Chart Outline" to '\uf044',
        "Pin" to '\uf045',
        "Pin Drop" to '\ue55e',
        "Pin End" to '\ue767',
        "Pin Invoke" to '\ue763',
        "Pinch" to '\ueb38',
        "Pivot Table Chart" to '\ue9ce',
        "Pix" to '\ueaa3',
        "Place" to '\ue55f',
        "Plagiarism" to '\uea5a',
        "Play Arrow" to '\ue037',
        "Play Circle" to '\ue1c4',
        "Play Circle Fill" to '\ue038',
        "Play Circle Filled" to '\ue038',
        "Play Circle Outline" to '\ue039',
        "Play Disabled" to '\uef6a',
        "Play For Work" to '\ue906',
        "Play Lesson" to '\uf047',
        "Playlist Add" to '\ue03b',
        "Playlist Add Check" to '\ue065',
        "Playlist Add Check Circle" to '\ue7e6',
        "Playlist Add Circle" to '\ue7e5',
        "Playlist Play" to '\ue05f',
        "Playlist Remove" to '\ueb80',
        "Plumbing" to '\uf107',
        "Plus One" to '\ue800',
        "Podcasts" to '\uf048',
        "Point Of Sale" to '\uf17e',
        "Policy" to '\uea17',
        "Poll" to '\ue801',
        "Polyline" to '\uebbb',
        "Polymer" to '\ue8ab',
        "Pool" to '\ueb48',
        "Portable Wifi Off" to '\ue0ce',
        "Portrait" to '\ue416',
        "Post Add" to '\uea20',
        "Power" to '\ue63c',
        "Power Input" to '\ue336',
        "Power Off" to '\ue646',
        "Power Settings New" to '\ue8ac',
        "Precision Manufacturing" to '\uf049',
        "Pregnant Woman" to '\ue91e',
        "Present To All" to '\ue0df',
        "Preview" to '\uf1c5',
        "Price Change" to '\uf04a',
        "Price Check" to '\uf04b',
        "Print" to '\ue8ad',
        "Print Disabled" to '\ue9cf',
        "Priority High" to '\ue645',
        "Privacy Tip" to '\uf0dc',
        "Private Connectivity" to '\ue744',
        "Production Quantity Limits" to '\ue1d1',
        "Propane" to '\uec14',
        "Propane Tank" to '\uec13',
        "Psychology" to '\uea4a',
        "Psychology Alt" to '\uf8ea',
        "Public" to '\ue80b',
        "Public Off" to '\uf1ca',
        "Publish" to '\ue255',
        "Published With Changes" to '\uf232',
        "Punch Clock" to '\ueaa8',
        "Push Pin" to '\uf10d',
        "Qr Code" to '\uef6b',
        "Qr Code 2" to '\ue00a',
        "Qr Code Scanner" to '\uf206',
        "Query Builder" to '\ue8ae',
        "Query Stats" to '\ue4fc',
        "Question Answer" to '\ue8af',
        "Question Mark" to '\ueb8b',
        "Queue" to '\ue03c',
        "Queue Music" to '\ue03d',
        "Queue Play Next" to '\ue066',
        "Quick Contacts Dialer" to '\ue0cf',
        "Quick Contacts Mail" to '\ue0d0',
        "Quickreply" to '\uef6c',
        "Quiz" to '\uf04c',
        "Quora" to '\uea98',
        "R Mobiledata" to '\uf04d',
        "Radar" to '\uf04e',
        "Radio" to '\ue03e',
        "Radio Button Checked" to '\ue837',
        "Radio Button Off" to '\ue836',
        "Radio Button On" to '\ue837',
        "Radio Button Unchecked" to '\ue836',
        "Railway Alert" to '\ue9d1',
        "Ramen Dining" to '\uea64',
        "Ramp Left" to '\ueb9c',
        "Ramp Right" to '\ueb96',
        "Rate Review" to '\ue560',
        "Raw Off" to '\uf04f',
        "Raw On" to '\uf050',
        "Read More" to '\uef6d',
        "Real Estate Agent" to '\ue73a',
        "Receipt" to '\ue8b0',
        "Receipt Long" to '\uef6e',
        "Recent Actors" to '\ue03f',
        "Recommend" to '\ue9d2',
        "Record Voice Over" to '\ue91f',
        "Rectangle" to '\ueb54',
        "Recycling" to '\ue760',
        "Reddit" to '\ueaa0',
        "Redeem" to '\ue8b1',
        "Redo" to '\ue15a',
        "Reduce Capacity" to '\uf21c',
        "Refresh" to '\ue5d5',
        "Remember Me" to '\uf051',
        "Remove" to '\ue15b',
        "Remove Circle" to '\ue15c',
        "Remove Circle Outline" to '\ue15d',
        "Remove Done" to '\ue9d3',
        "Remove From Queue" to '\ue067',
        "Remove Moderator" to '\ue9d4',
        "Remove Red Eye" to '\ue417',
        "Remove Road" to '\uebfc',
        "Remove Shopping Cart" to '\ue928',
        "Reorder" to '\ue8fe',
        "Repartition" to '\uf8e8',
        "Repeat" to '\ue040',
        "Repeat On" to '\ue9d6',
        "Repeat One" to '\ue041',
        "Repeat One On" to '\ue9d7',
        "Replay" to '\ue042',
        "Replay 10" to '\ue059',
        "Replay 30" to '\ue05a',
        "Replay 5" to '\ue05b',
        "Replay Circle Filled" to '\ue9d8',
        "Reply" to '\ue15e',
        "Reply All" to '\ue15f',
        "Report" to '\ue160',
        "Report Gmailerrorred" to '\uf052',
        "Report Off" to '\ue170',
        "Report Problem" to '\ue8b2',
        "Request Page" to '\uf22c',
        "Request Quote" to '\uf1b6',
        "Reset Tv" to '\ue9d9',
        "Restart Alt" to '\uf053',
        "Restaurant" to '\ue56c',
        "Restaurant Menu" to '\ue561',
        "Restore" to '\ue8b3',
        "Restore From Trash" to '\ue938',
        "Restore Page" to '\ue929',
        "Reviews" to '\uf054',
        "Rice Bowl" to '\uf1f5',
        "Ring Volume" to '\ue0d1',
        "Rocket" to '\ueba5',
        "Rocket Launch" to '\ueb9b',
        "Roller Shades" to '\uec12',
        "Roller Shades Closed" to '\uec11',
        "Roller Skating" to '\uebcd',
        "Roofing" to '\uf201',
        "Room" to '\ue8b4',
        "Room Preferences" to '\uf1b8',
        "Room Service" to '\ueb49',
        "Rotate 90 Degrees Ccw" to '\ue418',
        "Rotate 90 Degrees Cw" to '\ueaab',
        "Rotate Left" to '\ue419',
        "Rotate Right" to '\ue41a',
        "Roundabout Left" to '\ueb99',
        "Roundabout Right" to '\ueba3',
        "Rounded Corner" to '\ue920',
        "Route" to '\ueacd',
        "Router" to '\ue328',
        "Rowing" to '\ue921',
        "Rss Feed" to '\ue0e5',
        "Rsvp" to '\uf055',
        "Rtt" to '\ue9ad',
        "Rule" to '\uf1c2',
        "Rule Folder" to '\uf1c9',
        "Run Circle" to '\uef6f',
        "Running With Errors" to '\ue51d',
        "Rv Hookup" to '\ue642',
        "Safety Check" to '\uebef',
        "Safety Divider" to '\ue1cc',
        "Sailing" to '\ue502',
        "Sanitizer" to '\uf21d',
        "Satellite" to '\ue562',
        "Satellite Alt" to '\ueb3a',
        "Save" to '\ue161',
        "Save Alt" to '\ue171',
        "Save As" to '\ueb60',
        "Saved Search" to '\uea11',
        "Savings" to '\ue2eb',
        "Scale" to '\ueb5f',
        "Scanner" to '\ue329',
        "Scatter Plot" to '\ue268',
        "Schedule" to '\ue8b5',
        "Schedule Send" to '\uea0a',
        "Schema" to '\ue4fd',
        "School" to '\ue80c',
        "Science" to '\uea4b',
        "Score" to '\ue269',
        "Scoreboard" to '\uebd0',
        "Screen Lock Landscape" to '\ue1be',
        "Screen Lock Portrait" to '\ue1bf',
        "Screen Lock Rotation" to '\ue1c0',
        "Screen Rotation" to '\ue1c1',
        "Screen Rotation Alt" to '\uebee',
        "Screen Search Desktop" to '\uef70',
        "Screen Share" to '\ue0e2',
        "Screenshot" to '\uf056',
        "Screenshot Monitor" to '\uec08',
        "Scuba Diving" to '\uebce',
        "Sd" to '\ue9dd',
        "Sd Card" to '\ue623',
        "Sd Card Alert" to '\uf057',
        "Sd Storage" to '\ue1c2',
        "Search" to '\ue8b6',
        "Search Off" to '\uea76',
        "Security" to '\ue32a',
        "Security Update" to '\uf058',
        "Security Update Good" to '\uf059',
        "Security Update Warning" to '\uf05a',
        "Segment" to '\ue94b',
        "Select All" to '\ue162',
        "Self Improvement" to '\uea78',
        "Sell" to '\uf05b',
        "Send" to '\ue163',
        "Send And Archive" to '\uea0c',
        "Send Time Extension" to '\ueadb',
        "Send To Mobile" to '\uf05c',
        "Sensor Door" to '\uf1b5',
        "Sensor Occupied" to '\uec10',
        "Sensor Window" to '\uf1b4',
        "Sensors" to '\ue51e',
        "Sensors Off" to '\ue51f',
        "Sentiment Dissatisfied" to '\ue811',
        "Sentiment Neutral" to '\ue812',
        "Sentiment Satisfied" to '\ue813',
        "Sentiment Satisfied Alt" to '\ue0ed',
        "Sentiment Very Dissatisfied" to '\ue814',
        "Sentiment Very Satisfied" to '\ue815',
        "Set Meal" to '\uf1ea',
        "Settings" to '\ue8b8',
        "Settings Accessibility" to '\uf05d',
        "Settings Applications" to '\ue8b9',
        "Settings Backup Restore" to '\ue8ba',
        "Settings Bluetooth" to '\ue8bb',
        "Settings Brightness" to '\ue8bd',
        "Settings Cell" to '\ue8bc',
        "Settings Display" to '\ue8bd',
        "Settings Ethernet" to '\ue8be',
        "Settings Input Antenna" to '\ue8bf',
        "Settings Input Component" to '\ue8c0',
        "Settings Input Composite" to '\ue8c1',
        "Settings Input Hdmi" to '\ue8c2',
        "Settings Input Svideo" to '\ue8c3',
        "Settings Overscan" to '\ue8c4',
        "Settings Phone" to '\ue8c5',
        "Settings Power" to '\ue8c6',
        "Settings Remote" to '\ue8c7',
        "Settings Suggest" to '\uf05e',
        "Settings System Daydream" to '\ue1c3',
        "Settings Voice" to '\ue8c8',
        "Severe Cold" to '\uebd3',
        "Shape Line" to '\uf8d3',
        "Share" to '\ue80d',
        "Share Arrival Time" to '\ue524',
        "Share Location" to '\uf05f',
        "Shield" to '\ue9e0',
        "Shield Moon" to '\ueaa9',
        "Shop" to '\ue8c9',
        "Shop 2" to '\ue19e',
        "Shop Two" to '\ue8ca',
        "Shopify" to '\uea9d',
        "Shopping Bag" to '\uf1cc',
        "Shopping Basket" to '\ue8cb',
        "Shopping Cart" to '\ue8cc',
        "Shopping Cart Checkout" to '\ueb88',
        "Short Text" to '\ue261',
        "Shortcut" to '\uf060',
        "Show Chart" to '\ue6e1',
        "Shower" to '\uf061',
        "Shuffle" to '\ue043',
        "Shuffle On" to '\ue9e1',
        "Shutter Speed" to '\ue43d',
        "Sick" to '\uf220',
        "Sign Language" to '\uebe5',
        "Signal Cellular 0 Bar" to '\uf0a8',
        "Signal Cellular 1 Bar" to '\uf0a9',
        "Signal Cellular 2 Bar" to '\uf0aa',
        "Signal Cellular 3 Bar" to '\uf0ab',
        "Signal Cellular 4 Bar" to '\ue1c8',
        "Signal Cellular Alt" to '\ue202',
        "Signal Cellular Alt 1 Bar" to '\uebdf',
        "Signal Cellular Alt 2 Bar" to '\uebe3',
        "Signal Cellular Connected No Internet 0 Bar" to '\uf0ac',
        "Signal Cellular Connected No Internet 1 Bar" to '\uf0ad',
        "Signal Cellular Connected No Internet 2 Bar" to '\uf0ae',
        "Signal Cellular Connected No Internet 3 Bar" to '\uf0af',
        "Signal Cellular Connected No Internet 4 Bar" to '\ue1cd',
        "Signal Cellular No Sim" to '\ue1ce',
        "Signal Cellular Nodata" to '\uf062',
        "Signal Cellular Null" to '\ue1cf',
        "Signal Cellular Off" to '\ue1d0',
        "Signal Wifi 0 Bar" to '\uf0b0',
        "Signal Wifi 1 Bar" to '\uf0b1',
        "Signal Wifi 1 Bar Lock" to '\uf0b2',
        "Signal Wifi 2 Bar" to '\uf0b3',
        "Signal Wifi 2 Bar Lock" to '\uf0b4',
        "Signal Wifi 3 Bar" to '\uf0b5',
        "Signal Wifi 3 Bar Lock" to '\uf0b6',
        "Signal Wifi 4 Bar" to '\ue1d8',
        "Signal Wifi 4 Bar Lock" to '\ue1d9',
        "Signal Wifi Bad" to '\uf063',
        "Signal Wifi Connected No Internet 0" to '\uf0f2',
        "Signal Wifi Connected No Internet 1" to '\uf0ee',
        "Signal Wifi Connected No Internet 2" to '\uf0f1',
        "Signal Wifi Connected No Internet 3" to '\uf0ed',
        "Signal Wifi Connected No Internet 4" to '\uf064',
        "Signal Wifi Off" to '\ue1da',
        "Signal Wifi Statusbar 1 Bar" to '\uf0e6',
        "Signal Wifi Statusbar 2 Bar" to '\uf0f0',
        "Signal Wifi Statusbar 3 Bar" to '\uf0ea',
        "Signal Wifi Statusbar 4 Bar" to '\uf065',
        "Signal Wifi Statusbar Connected No Internet" to '\uf0f8',
        "Signal Wifi Statusbar Connected No Internet 1" to '\uf0e9',
        "Signal Wifi Statusbar Connected No Internet 2" to '\uf0f7',
        "Signal Wifi Statusbar Connected No Internet 3" to '\uf0e8',
        "Signal Wifi Statusbar Connected No Internet 4" to '\uf066',
        "Signal Wifi Statusbar Not Connected" to '\uf0ef',
        "Signal Wifi Statusbar Null" to '\uf067',
        "Signpost" to '\ueb91',
        "Sim Card" to '\ue32b',
        "Sim Card Alert" to '\ue624',
        "Sim Card Download" to '\uf068',
        "Single Bed" to '\uea48',
        "Sip" to '\uf069',
        "Skateboarding" to '\ue511',
        "Skip Next" to '\ue044',
        "Skip Previous" to '\ue045',
        "Sledding" to '\ue512',
        "Slideshow" to '\ue41b',
        "Slow Motion Video" to '\ue068',
        "Smart Button" to '\uf1c1',
        "Smart Display" to '\uf06a',
        "Smart Screen" to '\uf06b',
        "Smart Toy" to '\uf06c',
        "Smartphone" to '\ue32c',
        "Smoke Free" to '\ueb4a',
        "Smoking Rooms" to '\ueb4b',
        "Sms" to '\ue625',
        "Sms Failed" to '\ue626',
        "Snapchat" to '\uea6e',
        "Snippet Folder" to '\uf1c7',
        "Snooze" to '\ue046',
        "Snowboarding" to '\ue513',
        "Snowmobile" to '\ue503',
        "Snowshoeing" to '\ue514',
        "Soap" to '\uf1b2',
        "Social Distance" to '\ue1cb',
        "Solar Power" to '\uec0f',
        "Sort" to '\ue164',
        "Sort By Alpha" to '\ue053',
        "Sos" to '\uebf7',
        "Soup Kitchen" to '\ue7d3',
        "Source" to '\uf1c4',
        "South" to '\uf1e3',
        "South America" to '\ue7e4',
        "South East" to '\uf1e4',
        "South West" to '\uf1e5',
        "Spa" to '\ueb4c',
        "Space Bar" to '\ue256',
        "Space Dashboard" to '\ue66b',
        "Spatial Audio" to '\uebeb',
        "Spatial Audio Off" to '\uebe8',
        "Spatial Tracking" to '\uebea',
        "Speaker" to '\ue32d',
        "Speaker Group" to '\ue32e',
        "Speaker Notes" to '\ue8cd',
        "Speaker Notes Off" to '\ue92a',
        "Speaker Phone" to '\ue0d2',
        "Speed" to '\ue9e4',
        "Spellcheck" to '\ue8ce',
        "Splitscreen" to '\uf06d',
        "Spoke" to '\ue9a7',
        "Sports" to '\uea30',
        "Sports Bar" to '\uf1f3',
        "Sports Baseball" to '\uea51',
        "Sports Basketball" to '\uea26',
        "Sports Cricket" to '\uea27',
        "Sports Esports" to '\uea28',
        "Sports Football" to '\uea29',
        "Sports Golf" to '\uea2a',
        "Sports Gymnastics" to '\uebc4',
        "Sports Handball" to '\uea33',
        "Sports Hockey" to '\uea2b',
        "Sports Kabaddi" to '\uea34',
        "Sports Martial Arts" to '\ueae9',
        "Sports Mma" to '\uea2c',
        "Sports Motorsports" to '\uea2d',
        "Sports Rugby" to '\uea2e',
        "Sports Score" to '\uf06e',
        "Sports Soccer" to '\uea2f',
        "Sports Tennis" to '\uea32',
        "Sports Volleyball" to '\uea31',
        "Square" to '\ueb36',
        "Square Foot" to '\uea49',
        "Ssid Chart" to '\ueb66',
        "Stacked Bar Chart" to '\ue9e6',
        "Stacked Line Chart" to '\uf22b',
        "Stadium" to '\ueb90',
        "Stairs" to '\uf1a9',
        "Star" to '\ue838',
        "Star Border" to '\ue83a',
        "Star Border Purple500" to '\uf099',
        "Star Half" to '\ue839',
        "Star Outline" to '\uf06f',
        "Star Purple500" to '\uf09a',
        "Star Rate" to '\uf0ec',
        "Stars" to '\ue8d0',
        "Start" to '\ue089',
        "Stay Current Landscape" to '\ue0d3',
        "Stay Current Portrait" to '\ue0d4',
        "Stay Primary Landscape" to '\ue0d5',
        "Stay Primary Portrait" to '\ue0d6',
        "Sticky Note 2" to '\uf1fc',
        "Stop" to '\ue047',
        "Stop Circle" to '\uef71',
        "Stop Screen Share" to '\ue0e3',
        "Storage" to '\ue1db',
        "Store" to '\ue8d1',
        "Store Mall Directory" to '\ue563',
        "Storefront" to '\uea12',
        "Storm" to '\uf070',
        "Straight" to '\ueb95',
        "Straighten" to '\ue41c',
        "Stream" to '\ue9e9',
        "Streetview" to '\ue56e',
        "Strikethrough S" to '\ue257',
        "Stroller" to '\uf1ae',
        "Style" to '\ue41d',
        "Subdirectory Arrow Left" to '\ue5d9',
        "Subdirectory Arrow Right" to '\ue5da',
        "Subject" to '\ue8d2',
        "Subscript" to '\uf111',
        "Subscriptions" to '\ue064',
        "Subtitles" to '\ue048',
        "Subtitles Off" to '\uef72',
        "Subway" to '\ue56f',
        "Summarize" to '\uf071',
        "Superscript" to '\uf112',
        "Supervised User Circle" to '\ue939',
        "Supervisor Account" to '\ue8d3',
        "Support" to '\uef73',
        "Support Agent" to '\uf0e2',
        "Surfing" to '\ue515',
        "Surround Sound" to '\ue049',
        "Swap Calls" to '\ue0d7',
        "Swap Horiz" to '\ue8d4',
        "Swap Horizontal Circle" to '\ue933',
        "Swap Vert" to '\ue8d5',
        "Swap Vert Circle" to '\ue8d6',
        "Swap Vertical Circle" to '\ue8d6',
        "Swipe" to '\ue9ec',
        "Swipe Down" to '\ueb53',
        "Swipe Down Alt" to '\ueb30',
        "Swipe Left" to '\ueb59',
        "Swipe Left Alt" to '\ueb33',
        "Swipe Right" to '\ueb52',
        "Swipe Right Alt" to '\ueb56',
        "Swipe Up" to '\ueb2e',
        "Swipe Up Alt" to '\ueb35',
        "Swipe Vertical" to '\ueb51',
        "Switch Access Shortcut" to '\ue7e1',
        "Switch Access Shortcut Add" to '\ue7e2',
        "Switch Account" to '\ue9ed',
        "Switch Camera" to '\ue41e',
        "Switch Left" to '\uf1d1',
        "Switch Right" to '\uf1d2',
        "Switch Video" to '\ue41f',
        "Synagogue" to '\ueab0',
        "Sync" to '\ue627',
        "Sync Alt" to '\uea18',
        "Sync Disabled" to '\ue628',
        "Sync Lock" to '\ueaee',
        "Sync Problem" to '\ue629',
        "System Security Update" to '\uf072',
        "System Security Update Good" to '\uf073',
        "System Security Update Warning" to '\uf074',
        "System Update" to '\ue62a',
        "System Update Alt" to '\ue8d7',
        "System Update Tv" to '\ue8d7',
        "Tab" to '\ue8d8',
        "Tab Unselected" to '\ue8d9',
        "Table Bar" to '\uead2',
        "Table Chart" to '\ue265',
        "Table Restaurant" to '\ueac6',
        "Table Rows" to '\uf101',
        "Table View" to '\uf1be',
        "Tablet" to '\ue32f',
        "Tablet Android" to '\ue330',
        "Tablet Mac" to '\ue331',
        "Tag" to '\ue9ef',
        "Tag Faces" to '\ue420',
        "Takeout Dining" to '\uea74',
        "Tap And Play" to '\ue62b',
        "Tapas" to '\uf1e9',
        "Task" to '\uf075',
        "Task Alt" to '\ue2e6',
        "Taxi Alert" to '\uef74',
        "Telegram" to '\uea6b',
        "Temple Buddhist" to '\ueab3',
        "Temple Hindu" to '\ueaaf',
        "Terminal" to '\ueb8e',
        "Terrain" to '\ue564',
        "Text Decrease" to '\ueadd',
        "Text Fields" to '\ue262',
        "Text Format" to '\ue165',
        "Text Increase" to '\ueae2',
        "Text Rotate Up" to '\ue93a',
        "Text Rotate Vertical" to '\ue93b',
        "Text Rotation Angledown" to '\ue93c',
        "Text Rotation Angleup" to '\ue93d',
        "Text Rotation Down" to '\ue93e',
        "Text Rotation None" to '\ue93f',
        "Text Snippet" to '\uf1c6',
        "Textsms" to '\ue0d8',
        "Texture" to '\ue421',
        "Theater Comedy" to '\uea66',
        "Theaters" to '\ue8da',
        "Thermostat" to '\uf076',
        "Thermostat Auto" to '\uf077',
        "Thumb Down" to '\ue8db',
        "Thumb Down Alt" to '\ue816',
        "Thumb Down Off Alt" to '\ue9f2',
        "Thumb Up" to '\ue8dc',
        "Thumb Up Alt" to '\ue817',
        "Thumb Up Off Alt" to '\ue9f3',
        "Thumbs Up Down" to '\ue8dd',
        "Thunderstorm" to '\uebdb',
        "Tiktok" to '\uea7e',
        "Time To Leave" to '\ue62c',
        "Timelapse" to '\ue422',
        "Timeline" to '\ue922',
        "Timer" to '\ue425',
        "Timer 10" to '\ue423',
        "Timer 10 Select" to '\uf07a',
        "Timer 3" to '\ue424',
        "Timer 3 Select" to '\uf07b',
        "Timer Off" to '\ue426',
        "Tips And Updates" to '\ue79a',
        "Tire Repair" to '\uebc8',
        "Title" to '\ue264',
        "Toc" to '\ue8de',
        "Today" to '\ue8df',
        "Toggle Off" to '\ue9f5',
        "Toggle On" to '\ue9f6',
        "Token" to '\uea25',
        "Toll" to '\ue8e0',
        "Tonality" to '\ue427',
        "Topic" to '\uf1c8',
        "Tornado" to '\ue199',
        "Touch App" to '\ue913',
        "Tour" to '\uef75',
        "Toys" to '\ue332',
        "Track Changes" to '\ue8e1',
        "Traffic" to '\ue565',
        "Train" to '\ue570',
        "Tram" to '\ue571',
        "Transcribe" to '\uf8ec',
        "Transfer Within A Station" to '\ue572',
        "Transform" to '\ue428',
        "Transgender" to '\ue58d',
        "Transit Enterexit" to '\ue579',
        "Translate" to '\ue8e2',
        "Travel Explore" to '\ue2db',
        "Trending Down" to '\ue8e3',
        "Trending Flat" to '\ue8e4',
        "Trending Neutral" to '\ue8e4',
        "Trending Up" to '\ue8e5',
        "Trip Origin" to '\ue57b',
        "Troubleshoot" to '\ue1d2',
        "Try" to '\uf07c',
        "Tsunami" to '\uebd8',
        "Tty" to '\uf1aa',
        "Tune" to '\ue429',
        "Tungsten" to '\uf07d',
        "Turn Left" to '\ueba6',
        "Turn Right" to '\uebab',
        "Turn Sharp Left" to '\ueba7',
        "Turn Sharp Right" to '\uebaa',
        "Turn Slight Left" to '\ueba4',
        "Turn Slight Right" to '\ueb9a',
        "Turned In" to '\ue8e6',
        "Turned In Not" to '\ue8e7',
        "Tv" to '\ue333',
        "Tv Off" to '\ue647',
        "Two Wheeler" to '\ue9f9',
        "Type Specimen" to '\uf8f0',
        "U Turn Left" to '\ueba1',
        "U Turn Right" to '\ueba2',
        "Umbrella" to '\uf1ad',
        "Unarchive" to '\ue169',
        "Undo" to '\ue166',
        "Unfold Less" to '\ue5d6',
        "Unfold Less Double" to '\uf8cf',
        "Unfold More" to '\ue5d7',
        "Unfold More Double" to '\uf8d0',
        "Unpublished" to '\uf236',
        "Unsubscribe" to '\ue0eb',
        "Upcoming" to '\uf07e',
        "Update" to '\ue923',
        "Update Disabled" to '\ue075',
        "Upgrade" to '\uf0fb',
        "Upload" to '\uf09b',
        "Upload File" to '\ue9fc',
        "Usb" to '\ue1e0',
        "Usb Off" to '\ue4fa',
        "Vaccines" to '\ue138',
        "Vape Free" to '\uebc6',
        "Vaping Rooms" to '\uebcf',
        "Verified" to '\uef76',
        "Verified User" to '\ue8e8',
        "Vertical Align Bottom" to '\ue258',
        "Vertical Align Center" to '\ue259',
        "Vertical Align Top" to '\ue25a',
        "Vertical Distribute" to '\ue076',
        "Vertical Shades" to '\uec0e',
        "Vertical Shades Closed" to '\uec0d',
        "Vertical Split" to '\ue949',
        "Vibration" to '\ue62d',
        "Video Call" to '\ue070',
        "Video Camera Back" to '\uf07f',
        "Video Camera Front" to '\uf080',
        "Video Chat" to '\uf8a0',
        "Video Collection" to '\ue04a',
        "Video File" to '\ueb87',
        "Video Label" to '\ue071',
        "Video Library" to '\ue04a',
        "Video Settings" to '\uea75',
        "Video Stable" to '\uf081',
        "Videocam" to '\ue04b',
        "Videocam Off" to '\ue04c',
        "Videogame Asset" to '\ue338',
        "Videogame Asset Off" to '\ue500',
        "View Agenda" to '\ue8e9',
        "View Array" to '\ue8ea',
        "View Carousel" to '\ue8eb',
        "View Column" to '\ue8ec',
        "View Comfortable" to '\ue42a',
        "View Comfy" to '\ue42a',
        "View Comfy Alt" to '\ueb73',
        "View Compact" to '\ue42b',
        "View Compact Alt" to '\ueb74',
        "View Cozy" to '\ueb75',
        "View Day" to '\ue8ed',
        "View Headline" to '\ue8ee',
        "View In Ar" to '\ue9fe',
        "View Kanban" to '\ueb7f',
        "View List" to '\ue8ef',
        "View Module" to '\ue8f0',
        "View Quilt" to '\ue8f1',
        "View Sidebar" to '\uf114',
        "View Stream" to '\ue8f2',
        "View Timeline" to '\ueb85',
        "View Week" to '\ue8f3',
        "Vignette" to '\ue435',
        "Villa" to '\ue586',
        "Visibility" to '\ue8f4',
        "Visibility Off" to '\ue8f5',
        "Voice Chat" to '\ue62e',
        "Voice Over Off" to '\ue94a',
        "Voicemail" to '\ue0d9',
        "Volcano" to '\uebda',
        "Volume Down" to '\ue04d',
        "Volume Mute" to '\ue04e',
        "Volume Off" to '\ue04f',
        "Volume Up" to '\ue050',
        "Volunteer Activism" to '\uea70',
        "Vpn Key" to '\ue0da',
        "Vpn Key Off" to '\ueb7a',
        "Vpn Lock" to '\ue62f',
        "Vrpano" to '\uf082',
        "Wallet" to '\uf8ff',
        "Wallet Giftcard" to '\ue8f6',
        "Wallet Membership" to '\ue8f7',
        "Wallet Travel" to '\ue8f8',
        "Wallpaper" to '\ue75f',
        "Warehouse" to '\uebb8',
        "Warning" to '\ue002',
        "Warning Amber" to '\uf083',
        "Wash" to '\uf1b1',
        "Watch" to '\ue334',
        "Watch Later" to '\ue924',
        "Watch Off" to '\ueae3',
        "Water" to '\uf084',
        "Water Damage" to '\uf203',
        "Water Drop" to '\ue798',
        "Waterfall Chart" to '\uea00',
        "Waves" to '\ue176',
        "Waving Hand" to '\ue766',
        "Wb Auto" to '\ue42c',
        "Wb Cloudy" to '\ue42d',
        "Wb Incandescent" to '\ue42e',
        "Wb Iridescent" to '\ue436',
        "Wb Shade" to '\uea01',
        "Wb Sunny" to '\ue430',
        "Wb Twilight" to '\ue1c6',
        "Wc" to '\ue63d',
        "Web" to '\ue051',
        "Web Asset" to '\ue069',
        "Web Asset Off" to '\ue4f7',
        "Web Stories" to '\ue595',
        "Webhook" to '\ueb92',
        "Wechat" to '\uea81',
        "Weekend" to '\ue16b',
        "West" to '\uf1e6',
        "Whatshot" to '\ue80e',
        "Wheelchair Pickup" to '\uf1ab',
        "Where To Vote" to '\ue177',
        "Widgets" to '\ue75e',
        "Width Full" to '\uf8f5',
        "Width Normal" to '\uf8f6',
        "Width Wide" to '\uf8f7',
        "Wifi" to '\ue63e',
        "Wifi 1 Bar" to '\ue4ca',
        "Wifi 2 Bar" to '\ue4d9',
        "Wifi Calling" to '\uef77',
        "Wifi Calling 1" to '\uf0e7',
        "Wifi Calling 2" to '\uf0f6',
        "Wifi Calling 3" to '\uf085',
        "Wifi Channel" to '\ueb6a',
        "Wifi Find" to '\ueb31',
        "Wifi Lock" to '\ue1e1',
        "Wifi Off" to '\ue648',
        "Wifi Password" to '\ueb6b',
        "Wifi Protected Setup" to '\uf0fc',
        "Wifi Tethering" to '\ue1e2',
        "Wifi Tethering Error" to '\uf086',
        "Wifi Tethering Error Rounded" to '\uf086',
        "Wifi Tethering Off" to '\uf087',
        "Wind Power" to '\uec0c',
        "Window" to '\uf088',
        "Wine Bar" to '\uf1e8',
        "Woman" to '\ue13e',
        "Woman 2" to '\uf8e7',
        "Woo Commerce" to '\uea6d',
        "Wordpress" to '\uea9f',
        "Work" to '\ue8f9',
        "Work History" to '\uec09',
        "Work Off" to '\ue942',
        "Work Outline" to '\ue943',
        "Workspace Premium" to '\ue7af',
        "Workspaces" to '\ue1a0',
        "Wrap Text" to '\ue25b',
        "Wrong Location" to '\uef78',
        "Wysiwyg" to '\uf1c3',
        "Yard" to '\uf089',
        "Youtube Searched For" to '\ue8fa',
        "Zoom In" to '\ue8ff',
        "Zoom In Map" to '\ueb2d',
        "Zoom Out" to '\ue900',
        "Zoom Out Map" to '\ue56b'
    )

    // Unified search returning all icon names (ImageVector + Char-based)
    fun searchAllIconNames(query: String): List<String> {
        return (allIcons.keys + fontCodepointIcons.keys)
            .distinct()
            .filter { it.contains(query, ignoreCase = true) }
            .sorted()
    }

    // Get only ImageVector-based results for classic usage
    fun searchIcons(query: String): List<Pair<String, ImageVector>> {
        return allIcons
            .filterKeys { it.contains(query, ignoreCase = true) }
            .toList()
            .sortedBy { it.first }
    }


    fun getAllIconNames(): List<String> {
        return (allIcons.keys + fontCodepointIcons.keys).distinct().sorted()
    }


    // Fetch ImageVector
    fun getIconByName(name: String): ImageVector? = allIcons[name]

    // Fetch Char
    fun getCodepointByName(name: String): Char = fontCodepointIcons[name] ?: '\ue838' // Star default

    // Render any codepoint-based icon using font
    @Composable
    fun RenderIcon(
        name: String,
        modifier: Modifier = Modifier,
        color: Color = MaterialTheme.colorScheme.onSurface,
        fontSizeSp: Int = 28
    ) {
        val char = getCodepointByName(name)
        val fontFamily = remember {
            FontFamily(Font(R.font.materialiconstwotone_regular))
        }

        Text(
            text = char.toString(),
            fontSize = fontSizeSp.sp,
            fontFamily = fontFamily,
            fontWeight = FontWeight.Normal,
            color = color,
            modifier = modifier
        )
    }

}
