@startuml TiMEModelDiagram

class TiME {
  - id: String
  - title: String
  - note: String?
  - startTime: Long
  - endTime: Long
  - categoryId: String?
  - iconName: String?
  - createdAt: Long
  - isCompleted: Boolean
  - subtasks: List<String>?
}

@enduml
